importing the labraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import the dataset

In [3]:
data = pd.read_csv('/content/Diabetes_data.csv')
data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

initiating the variables

In [6]:
x = data.drop(['Outcome'], axis=1)
y = data['Outcome'].values.reshape(-1,1)

Splitting dataset into training and testing dataset

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)

using feature scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train
x_test

array([[ 0.68185612, -0.71402038, -0.61712658, ...,  0.26073561,
        -0.11637247,  0.87809089],
       [-0.52639686, -0.27664283,  0.30191569, ...,  0.48053518,
        -0.954231  , -1.03594038],
       [-0.52639686, -0.40160784, -0.29275872, ..., -0.15300476,
        -0.9245197 , -1.03594038],
       ...,
       [ 1.28598261, -0.80774414,  0.13973176, ...,  0.62275843,
         0.04703966,  2.0961108 ],
       [-0.52639686,  0.78555979,  0.03160914, ..., -0.51502758,
        -0.39268751, -0.33992901],
       [ 1.28598261, -1.46381046,  0.03160914, ...,  0.42881763,
         0.70068816,  0.53008521]])

using logistic regression

In [9]:
#traing our model using Logistic Regression
from sklearn.linear_model import LogisticRegression
lgr=LogisticRegression()
lgr.fit(x_train, y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

testing the model

In [33]:
y_pred1=lgr.predict(x_test)

making the confusion matrix

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test, y_pred1)
print(cm)
accuracy_score(y_test, y_pred1)

[[79 20]
 [18 37]]


0.7532467532467533

using KNeighbor classifier

In [36]:
from sklearn.neighbors import KNeighborsClassifier
knc=KNeighborsClassifier()
knc.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

testing the result

In [37]:
y_pred2=knc.predict(x_test)

making the confusion matrix

In [40]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred2)
print(cm)
accuracy_score(y_test, y_pred2)

[[79 20]
 [27 28]]


0.6948051948051948

using decision tree

In [41]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train, y_train)


DecisionTreeClassifier()

In [42]:
y_pred3=dtc.predict(x_test)

In [43]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred3)
print(cm)
accuracy_score(y_test, y_pred3)

[[77 22]
 [16 39]]


0.7532467532467533

using Support vector machine

In [44]:
from sklearn.svm import SVC
svcclassifier=SVC(kernel='linear')
svcclassifier.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [45]:
y_pred4=svcclassifier.predict(x_test)

In [46]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred4)
print(cm)
accuracy_score(y_test, y_pred4)

[[81 18]
 [19 36]]


0.7597402597402597

printing the result of Accuracy

In [48]:
print('accuracy by logistic regression  :', accuracy_score(y_test, y_pred1))
print('accuracy by KNN  :', accuracy_score(y_test, y_pred2))
print('accuracy by decision tree  :', accuracy_score(y_test, y_pred3))
print('accuracy by SVM  :', accuracy_score(y_test, y_pred4))

accuracy by logistic regression  : 0.7532467532467533
accuracy by KNN  : 0.6948051948051948
accuracy by decision tree  : 0.7532467532467533
accuracy by SVM  : 0.7597402597402597


In [49]:
print('Enter the information below:')
Pregnancies = int(input("Pregnancies  :"))
Glucose = float(input("Glucose  :"))
BloodPressure = float(input("BloodPressure  :"))
SkineThikness = float(input("SkineThikness  :"))
Insulin = float(input("Insulin  :"))
BMI = float(input("BMI  :"))
DiabetesPedigreeFunction = float(input("DiabetesPedigreeFunction  :"))
Age = float(input("Age  :"))
output = knc.predict([[Pregnancies,Glucose,BloodPressure,SkineThikness,Insulin,BMI,DiabetesPedigreeFunction,Age]])
if output ==1:
  print("Patient is suffering from Diabetes")
else:
  print("Patient is not suffering from Diabetes")


Enter the information below:
Pregnancies  :51
Glucose  :180
BloodPressure  :81
SkineThikness  :23
Insulin  :1
BMI  :35.2
DiabetesPedigreeFunction  :0.23
Age  :45
Patient is suffering from Diabetes
